/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-03-24 04:18:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.w20200324;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jQueryEx12_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>jQueryEx12.jsp</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t// 각 버튼을 누르면 기능을 수행\r\n");
      out.write("\t\t$('input[value=\"숨기기\"]').on('click', function(){\r\n");
      out.write("\t\t\t$('#box1').hide(3000);\t\t// 함수 안에 밀리세컨드(1/1000초) 단위로 시간 지정\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('input[value=\"보이기\"]').click(function(){\r\n");
      out.write("\t\t\t$('#box1').show(3000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('input[value=\"번갈아 수행\"]').click(function(){\r\n");
      out.write("\t\t\t$('#box1').toggle(3000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('input[value=\"점점 사라지기\"]').click(function(){\r\n");
      out.write("\t\t\t$('#box1').fadeOut(3000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('input[value=\"점점 보이기\"]').click(function(){\r\n");
      out.write("\t\t\t$('#box1').fadeIn(3000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('input[value=\"이어서 효과 주기\"]').click(function(){\r\n");
      out.write("\t\t\t// 하나의 화면 효과(effect)가 끝나고 다른 함수를 붙일 수 있음\r\n");
      out.write("\t\t\t// ex) 다른 페이지로 이동..\r\n");
      out.write("\t\t\t$(\"#box\").slideToggle(1000, function(){\r\n");
      out.write("\t\t\t\talert(\"작업 완료\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<input type=\"button\" value=\"숨기기\" />\r\n");
      out.write("\t<input type=\"button\" value=\"보이기\" />\r\n");
      out.write("\t<input type=\"button\" value=\"번갈아 수행\" />\r\n");
      out.write("\t<input type=\"button\" value=\"점점 사라지기\" />\r\n");
      out.write("\t<input type=\"button\" value=\"점점 보이기\" />\r\n");
      out.write("\t<input type=\"button\" value=\"이어서 효과 주기\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"box1\" style=\"font-size: 20px\">\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t오늘은 화요일 <br /><br />\r\n");
      out.write("\t\t내일은 수요일 <br /><br />\r\n");
      out.write("\t\t곧 점심시간 <br /><br />\r\n");
      out.write("\t\t배고파 <br /><br />\r\n");
      out.write("\t\t모레 쯤 조 편성을 하지 않을까?<br /><br />\r\n");
      out.write("\t\t모레부터 비가 온다<br /><br />\r\n");
      out.write("\t\tLorem ipsum dolor sit amet, consectetur adipisicing elit. \r\n");
      out.write("\t\tVeniam voluptas repellendus iusto illo deseruntid nobis ipsam commodi eos aliquam tenetur laboriosam culpa pariatur. \r\n");
      out.write("\t\tDolorem dicta dolorum tenetur corporis eum.\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
